services:
  - type: web
    name: givta-backend
    env: node
    # This region will be applied on your next deploy. Ensure your Redis instance is also in this region.
    region: Oregon (US West)
    plan: free

    # These commands will be run from the 'rootDir' directory.
    buildCommand: npm install && npm run build
    startCommand: npm start

    # The rootDir is '.' because render.yaml is already inside the 'Backend' directory.
    rootDir: .

    # Non-sensitive environment variables.
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: FIREBASE_PROJECT_ID
        value: givta-94cb8
      - key: ALLOWED_ORIGINS
        value: https://givta.app,https://givta-admin.netlify.app,exp://exp.host
      - key: ENABLE_WHATSAPP_BOT
        value: "true" # or "false"

      # --- Secrets Management ---
      # These 'fromSecret' keys reference secret variables you must create in the Render dashboard
      # under your service's 'Environment' tab.
      - key: JWT_SECRET
        fromSecret: JWT_SECRET # Name of the secret variable in Render
      - key: JWT_REFRESH_SECRET
        fromSecret: JWT_REFRESH_SECRET # Name of the secret variable in Render
      - key: PAYSTACK_SECRET_KEY
        fromSecret: PAYSTACK_SECRET_KEY # Name of the secret variable in Render
      - key: PAYSTACK_PUBLIC_KEY
        fromSecret: PAYSTACK_PUBLIC_KEY # Name of the secret variable in Render

      # This references a secret file you create in the Render dashboard for your Firebase credentials.
      - key: GOOGLE_APPLICATION_CREDENTIALS
        fromSecretFile: /etc/secrets/firebase_credentials # Path to the secret file on Render

      # This automatically connects to your Render Redis service.
      - key: REDIS_URL
        fromService:
          type: redis
          name: givta-redis # Ensure this matches the name of your Render Redis service
    healthCheckPath: /api/health
    # Auto-deploy is enabled, so any 'git push' to your main branch will trigger a new deployment.
    autoDeploy: true
